/*
 Copyright (C) 2026 Nikita Rabykin

 This file is part of TrenchBroom.

 TrenchBroom is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 TrenchBroom is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with TrenchBroom. If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include "base/Result.h"

#include <filesystem>
#include <functional>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <string_view>
#include <vector>

namespace tb::mcp
{

// The user manual behind manual_search, manual_section and the manual resources: the
// HTML file that the build generates from the manual's Markdown source with pandoc, and
// the keyboard shortcut table (shortcuts.js) that the build writes next to it.

/** A section of the manual: a heading and the text up to the next heading. */
struct ManualSection
{
  /** The heading's anchor id, e.g. "camera_navigation". */
  std::string id;
  std::string title;
  /** The heading level, 1 to 6. */
  size_t level = 1;
  /** The index of the enclosing section, if any. */
  std::optional<size_t> parent;
  /** The indices of the directly nested sections. */
  std::vector<size_t> children;
  /**
   * The section's own text (without the heading and the nested sections) as Markdown.
   * References to menu items, actions and keys are placeholders; see resolveManualText.
   */
  std::string text;
};

struct Manual
{
  /** The document title, e.g. "TrenchBroom 2026.1 Reference Manual". */
  std::string title;
  /** All sections in document order. */
  std::vector<ManualSection> sections;

  /**
   * Finds a section by id, or else by title (both case-insensitive; a leading '#' is
   * ignored).
   */
  std::optional<size_t> find(std::string_view idOrTitle) const;

  /** The titles of the enclosing sections of the given section, outermost first. */
  std::vector<std::string> titlePath(size_t index) const;
};

/**
 * Parses a manual generated by pandoc: the headings (h1 to h6 with an id) start the
 * sections; paragraphs, lists, tables, code blocks, figures, definition lists and links
 * become Markdown; HTML entities are decoded. Only the article with the id
 * "content_body" is read if there is one (the manual template's table of contents is
 * skipped), else the body.
 */
Manual parseManual(std::string_view html);

/** The kinds of references that the manual's scripts insert. */
enum class ManualReference
{
  /** print_menu_item("Menu/View/..."): a menu item with its shortcut. */
  MenuItem,
  /** print_action("Controls/..."): the shortcut of an action or key preference. */
  Action,
  /** print_key("Alt"): a key name. */
  Key,
};

/** Returns the text for a reference; the key is the script's argument. */
using ManualReferenceResolver =
  std::function<std::string(ManualReference kind, const std::string& key)>;

/** Replaces the reference placeholders in a section's text. */
std::string resolveManualText(
  std::string_view text, const ManualReferenceResolver& resolver);

/** The keyboard shortcut table of the manual (shortcuts.js). */
struct ManualShortcuts
{
  struct MenuItem
  {
    /** The menu path with the item's label, e.g. {"View", "Maximize Current View"}. */
    std::vector<std::string> path;
    /** The default shortcuts in portable text, e.g. "Ctrl+Space". */
    std::vector<std::string> shortcuts;
  };

  std::map<std::string, MenuItem, std::less<>> menu;
  std::map<std::string, std::vector<std::string>, std::less<>> actions;
  std::map<std::string, std::string, std::less<>> keys;
};

/** Parses shortcuts.js. Unparsable entries are skipped. */
ManualShortcuts parseManualShortcuts(std::string_view js);

/** A manual loaded from disk. */
struct LoadedManual
{
  std::filesystem::path path;
  Manual manual;
  /** The shortcut table next to the manual, if there is one. */
  std::optional<ManualShortcuts> shortcuts;
};

/**
 * Loads and parses the manual at the given path together with the shortcuts.js next to
 * it. The result is cached by path, size and modification time.
 */
Result<std::shared_ptr<const LoadedManual>> loadManual(const std::filesystem::path& path);

} // namespace tb::mcp
